### PR TITLE
reroute from profile if not logged in

### PR DESCRIPTION
**Pull request by KEINance**
small lag but works if anyone can figure out the import issue by all means have at it haha

### CODE REVIEW

**Review by Akemp24 — APPROVED** [review]

**Comment by KEINance** [comment]
DON'T MERGE THIS ONE I HAVE TO PULL THE LAST PUSH THEN i WILL RESUBMIT

**Comment by KEINance** [comment]
Should be ready for you guys to finish approving

**Review by TheWiseSailor — APPROVED** [review]
looms Good!!!

**Comment by TheWiseSailor** [comment]
looks good*

**Pull request merged**
